{% set name = "sparse_dot_mkl" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 70a683448a8d23873ec8687d26930ab61509f7f7586530cc8ad2ce50f2216ef3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
  run:
    - numpy >=1.16
    - python
    - scipy >=1.0
    - mkl >=2020.0

test:
  imports:
    - sparse_dot_mkl
    - sparse_dot_mkl.tests
  requires:
    - coverage
    - nose
  commands:
    - python -c "import sparse_dot_mkl.tests.test_mkl; sparse_dot_mkl.tests.test_mkl.run()"

about:
  home: https://github.com/flatironinstitute/sparse_dot
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Intel MKL wrapper for sparse matrix multiplication
  description: |
    This package is a ctypes wrapper for the Math Kernel Library matrix multiplicaton.
    It will dot product numpy dense arrays and scipy sparse arrays (multithreaded)

extra:
  recipe-maintainers:
    - asistradition
